// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3fUQ-cRwiPmSqz1x8UqrPViMJ-tVuLXQ',
    appId: '1:793999692902:web:b8bb3140ff9fff47bb49a7',
    messagingSenderId: '793999692902',
    projectId: 'gymmanagement-b78e2',
    authDomain: 'gymmanagement-b78e2.firebaseapp.com',
    storageBucket: 'gymmanagement-b78e2.appspot.com',
    measurementId: 'G-HJTX8DE0MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO4SzSALAghYKj8V-Bsd3AHQTEPyOM0qY',
    appId: '1:793999692902:android:f202d2e63fa9ed00bb49a7',
    messagingSenderId: '793999692902',
    projectId: 'gymmanagement-b78e2',
    storageBucket: 'gymmanagement-b78e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpKpO5Bxow-AfwyrifVOWfmz7slhXrunE',
    appId: '1:793999692902:ios:acbe92574934f655bb49a7',
    messagingSenderId: '793999692902',
    projectId: 'gymmanagement-b78e2',
    storageBucket: 'gymmanagement-b78e2.appspot.com',
    iosBundleId: 'com.codeforany.workoutFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpKpO5Bxow-AfwyrifVOWfmz7slhXrunE',
    appId: '1:793999692902:ios:486ae61f1ef99a36bb49a7',
    messagingSenderId: '793999692902',
    projectId: 'gymmanagement-b78e2',
    storageBucket: 'gymmanagement-b78e2.appspot.com',
    iosBundleId: 'project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3fUQ-cRwiPmSqz1x8UqrPViMJ-tVuLXQ',
    appId: '1:793999692902:web:3204d042078c8d5bbb49a7',
    messagingSenderId: '793999692902',
    projectId: 'gymmanagement-b78e2',
    authDomain: 'gymmanagement-b78e2.firebaseapp.com',
    storageBucket: 'gymmanagement-b78e2.appspot.com',
    measurementId: 'G-8PWFECZZ68',
  );
}
